name: Xenial.BTool

on:
  push:
    branches: [master]
    tags: [v*]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
      - name: Setup .NET6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Build
        run: dotnet run --project build/build.csproj pack
      - uses: actions/upload-artifact@v2
        if: runner.os == 'Windows' && startsWith(github.ref, 'refs/tags/v')
        with:
          name: nuget
          path: artifacts/nuget/
  deploy-packages:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Fetch all history for all tags and branches
        run: |
          git fetch --prune --unshallow
      - uses: actions/download-artifact@v2
        with:
          name: nuget
          path: artifacts/nuget/
      - name: Setup .NET6
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Publish to nuget.org
        run: dotnet run --project build/build.csproj deploy
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET_API_KEY}}
